### ISSUE TITLE
"nan" à la place du z-score

### ISSUE THREAD

**Issue by Hoxus** [dridk/ion-wisecondor#4]
Bonjour,

Je cherche à réinstaller le plugin IonWiseCondor à l'hopital de la Timone après une réinstallation du serveur proton vers une version plus récente (Ubuntu 14.04, TS 5.2.2).
L'installation semble être OK, et après analyse, les graphs sont bien générés mais les Z-scores ne sont pas (tous) affichés : seul le 18 est indiqué.

Le log de l'analyse (que je joins en pj) mentionne une erreur au milieu du flux d'informations.
```
ERROR:ion.plugin.runtime:Plugin execution failed
INFO:ion.plugin.runtime:Plugin complete: 'IonWisecondor' v2.0i -- exit_status = -1
```

Bien que ce message semble annoncer que le plugin a planté, il continue l'analyse.
Je ne sais pas si l'absence des Z-scores sur la page de résultats et cette erreur sont liés ?
Dans tous les cas, j'aimerais pouvoir lire les Z-scores directement dans l'interface TB.
Pouvez-vous m'aider ?

Cordialement,
AA

capture TB:
![image](https://cloud.githubusercontent.com/assets/10241614/23618358/691a524a-0290-11e7-828f-148d5cf52787.png)
[drmaa_stdout.txt](https://github.com/dridk/ion-wisecondor/files/821717/drmaa_stdout.txt)

**Comment by Hoxus** [comment]
Bonjour,

Après avoir décortiqué les différents scripts, l'affichage de ces "nan" values vient de leur présence dans  "zSmoothDict" lu depuis le fichier IonXpress_XXX_date.tested.
Le résultat d'une somme ou d'une division d'une liste de nombres et nan produit nan.
**Cependant je ne sais si c'est normal ??**

Si oui, je peux utiliser numpy.nansum pour les écarter, mais par curiosité, j'aimerais savoir pourquoi cela fonctionnait avant.

Merci,
AA

**Comment by dridk** [comment]
Fix with 27fafd5e03b957427572a7e54899aee04acdb5f2
